name: bomb_complex
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  # ทำ Launcher Icon
  flutter_launcher_icons: ^0.13.1

  # ทำ Splash Screen
  flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true

  assets:
    - assets/splash/icon.png

# -----------------------------
# SPLASH SCREEN CONFIG
# -----------------------------
flutter_native_splash:
  color: "#ffffff"
  image: assets/splash/icon.png

  android: true
  ios: true
  web: false

  android_12:
    color: "#ffffff"
    image: assets/splash/icon.png

# -----------------------------
# LAUNCHER ICON CONFIG
# -----------------------------
flutter_icons:
  android: true
  ios: true
  image_path: "assets/splash/icon.png"
